language: erlang
otp_release:
  - 18.3
  - 19.0
  - 19.3
  - 20.0


env:
  - TEST=1
before_script:
    - kerl list installations

script:
  - ./support/rebar3 ct
  - ./support/rebar3 dialyzer

cache:
  directories:
    - $HOME/.cache/rebar3
